apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: FwoGZXIvYXdzEB8aDPQi+TLjlS1zmg3zEyLVAba4k3i2XauFMB4YXC3Ajai2P+uDfCoCaBWccDI5oK9PMuMgF9EaiCAweisUGrl0BvApsYfmHB9PKMDdNilJ3HpNqCih6vzAh061qEcph3SjEo/F2968gpg6JxbaRQWx6vkA0ka4VovbMY5MKa6VNHLzS/uQXGhj8PevJDKPtCukhwy1LH/7KGp6omIRhHVwFO1hkIDDySfm0VOegctkYs7olUI8n9JXhGdemJEh9onXx2RBfzXI/2/1cnGTiIGGurY2fCKjnrFa5W+hz5m68r0WYV2g0yjUkOuoBjItzZ3x6gUl1utwrmFmXZ3rOe4DFU/MZMP7FJpG+O7feEc069kSTfiBhRJWixcw